In [34]:
import pandas as pd
import numpy as np

In [35]:
pd.set_option('display.max_columns', None)

### Cleaning dataset

We're in presence of a panel dataset. We choose to only select observations for the year `2012`. 
We're also gonna convert the `Adult Mortality` continuous variable into a categorical variable.

In [36]:
df = pd.read_csv("dataset/life-expectancy.csv", sep=",", decimal=".")
print(df.shape)
print(df.columns)
df.head()

(2938, 22)
Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [33]:
df.rename(str.strip, axis=1, inplace=True)
df.columns = df.columns.str.lower()
df.rename({"thinness  1-19 years": "thinness 10-19 years"}, axis=1, inplace=True)
df["thinness  1-19 years"].rename("thinness 10-19 years", inplace=True)

print(df.columns)
df.head()

/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/3566121785.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(str.strip, axis=1, inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/3566121785.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename({"thinness  1-19 years": "thinness 10-19 years"}, axis=1, inplace=True)

KeyError: 'thinness  1-19 years'

In [24]:
df = df[df["year"] == 2012]
print(df.shape)
df.head()

(183, 22)

,country,year,status,life expectancy,adult mortality,infant deaths,alcohol,percentage expenditure,hepatitis b,measles,bmi,under-five deaths,polio,total expenditure,diphtheria,hiv/aids,gdp,population,thinness 1-19 years,thinness 5-9 years,income composition of resources,schooling
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
19,Albania,2012,Developing,76.9,86.0,0,5.14,412.443356,99.0,9,55.8,1,99.0,5.59,99.0,0.1,4247.614380,2941.0,1.3,1.4,0.752,14.2
35,Algeria,2012,Developing,75.1,113.0,21,0.66,555.926083,95.0,18,56.1,24,95.0,6.14,95.0,0.1,5564.825660,37565847.0,5.9,5.8,0.732,14.4
51,Angola,2012,Developing,56.0,358.0,72,8.24,256.122524,75.0,4458,21.5,110,75.0,3.30,75.0,2.6,4598.249988,259615.0,8.8,8.6,0.508,10.3
67,Antigua and Barbuda,2012,Developing,75.9,134.0,0,8.18,2156.229842,98.0,0,45.7,0,97.0,5.39,98.0,0.2,12565.441970,NaN,3.3,3.3,0.778,13.8

In [25]:
df["adult mortality"] = pd.cut(df["adult mortality"], [0, 50, 80, 150, 350, df["adult mortality"].max()], labels=["very low", "low", "middle", "high", "very high"])

/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/1278151862.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["adult mortality"] = pd.cut(df["adult mortality"], [0, 50, 80, 150, 350, df["adult mortality"].max()], labels=["very low", "low", "middle", "high", "very high"])

In [26]:
df.head()

,country,year,status,life expectancy,adult mortality,infant deaths,alcohol,percentage expenditure,hepatitis b,measles,bmi,under-five deaths,polio,total expenditure,diphtheria,hiv/aids,gdp,population,thinness 1-19 years,thinness 5-9 years,income composition of resources,schooling
3,Afghanistan,2012,Developing,59.5,high,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
19,Albania,2012,Developing,76.9,middle,0,5.14,412.443356,99.0,9,55.8,1,99.0,5.59,99.0,0.1,4247.614380,2941.0,1.3,1.4,0.752,14.2
35,Algeria,2012,Developing,75.1,middle,21,0.66,555.926083,95.0,18,56.1,24,95.0,6.14,95.0,0.1,5564.825660,37565847.0,5.9,5.8,0.732,14.4
51,Angola,2012,Developing,56.0,very high,72,8.24,256.122524,75.0,4458,21.5,110,75.0,3.30,75.0,2.6,4598.249988,259615.0,8.8,8.6,0.508,10.3
67,Antigua and Barbuda,2012,Developing,75.9,middle,0,8.18,2156.229842,98.0,0,45.7,0,97.0,5.39,98.0,0.2,12565.441970,NaN,3.3,3.3,0.778,13.8

In [27]:
df.isna().sum()

country                             0
year                                0
status                              0
life expectancy                     0
adult mortality                     0
infant deaths                       0
alcohol                             1
percentage expenditure              0
hepatitis b                        13
measles                             0
bmi                                 2
under-five deaths                   0
polio                               0
total expenditure                   2
diphtheria                          0
hiv/aids                            0
gdp                                29
population                         41
thinness  1-19 years                2
thinness 5-9 years                  2
income composition of resources    10
schooling                          10
dtype: int64

In [28]:
for feature in df.columns:
    df.dropna(subset=[feature], inplace=True)
    
df.drop("year", axis=1, inplace=True)

df.head()

/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=[feature], inplace=True)
/var/folders/zn/_2h7w2j547357vpm3_5pxrsr0000gn/T/ipykernel_22880/209012276.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop("year", axis=1, inplace=True)

,country,status,life expectancy,adult mortality,infant deaths,alcohol,percentage expenditure,hepatitis b,measles,bmi,under-five deaths,polio,total expenditure,diphtheria,hiv/aids,gdp,population,thinness 1-19 years,thinness 5-9 years,income composition of resources,schooling
3,Afghanistan,Developing,59.5,high,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
19,Albania,Developing,76.9,middle,0,5.14,412.443356,99.0,9,55.8,1,99.0,5.59,99.0,0.1,4247.614380,2941.0,1.3,1.4,0.752,14.2
35,Algeria,Developing,75.1,middle,21,0.66,555.926083,95.0,18,56.1,24,95.0,6.14,95.0,0.1,5564.825660,37565847.0,5.9,5.8,0.732,14.4
51,Angola,Developing,56.0,very high,72,8.24,256.122524,75.0,4458,21.5,110,75.0,3.30,75.0,2.6,4598.249988,259615.0,8.8,8.6,0.508,10.3
83,Argentina,Developing,75.9,very low,9,8.35,1133.558003,91.0,2,61.0,10,99.0,5.20,91.0,0.1,12969.771200,4296739.0,1.0,0.9,0.822,17.2

In [29]:
df.shape

(129, 21)

In [30]:
df.to_csv("dataset/life-expectancy-2012.csv", index=False)